import { Room } from '../types/room';

export const MOCK_ROOMS: Room[] = [
  {
    id: 'room-a101',
    name: 'Phòng Thảo Luận A101',
    building: 'A',
    floor: 1,
    capacity: 6,
    equipment: ['whiteboard', 'ac', 'projector'],
    photoUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    description: 'Phòng học nhóm nhỏ yên tĩnh tại tầng 1 tòa A, trang bị bảng kính và máy chiếu Sony siêu nét.',
  },
  {
    id: 'room-a204',
    name: 'Phòng Hội Thảo A204',
    building: 'A',
    floor: 2,
    capacity: 25,
    equipment: ['projector', 'whiteboard', 'ac'],
    photoUrl: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=800&q=80',
    status: 'occupied',
    description: 'Phòng họp & thuyết trình quy mô trung bình, âm thanh hội thảo chuyên dụng.',
  },
  {
    id: 'room-b102',
    name: 'Phòng Học Nhóm B102',
    building: 'B',
    floor: 1,
    capacity: 8,
    equipment: ['whiteboard', 'ac'],
    photoUrl: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    description: 'Bố trí bàn tròn thảo luận nhóm linh hoạt, ổ cắm sạc laptop tại từng vị trí ngồi.',
  },
  {
    id: 'room-b205',
    name: 'Không Gian Sáng Tạo B205',
    building: 'B',
    floor: 2,
    capacity: 15,
    equipment: ['projector', 'whiteboard', 'ac'],
    photoUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    description: 'Thiết kế mở hiện đại, ghế lười và bàn làm việc nhóm năng động cho sinh viên CNTT.',
  },
  {
    id: 'room-b301',
    name: 'Phòng Nghiên Cứu B301',
    building: 'B',
    floor: 3,
    capacity: 4,
    equipment: ['whiteboard', 'ac'],
    photoUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=800&q=80',
    status: 'occupied',
    description: 'Không gian cách âm tuyệt đối dành cho các nhóm làm đồ án tốt nghiệp và nghiên cứu khoa học.',
  },
  {
    id: 'room-c105',
    name: 'Phòng Lab AI & Data C105',
    building: 'C',
    floor: 1,
    capacity: 30,
    equipment: ['high_spec_pc', 'projector', 'ac'],
    photoUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    description: 'Dàn 30 máy tính Core i7 RTX 4070 chuyên dụng cho huấn luyện mô hình học sâu và đồ họa 3D.',
  },
  {
    id: 'room-c202',
    name: 'Phòng Lab An Toàn Thông Tin C202',
    building: 'C',
    floor: 2,
    capacity: 35,
    equipment: ['high_spec_pc', 'projector', 'ac', 'whiteboard'],
    photoUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
    status: 'occupied',
    description: 'Trang bị hạ tầng mạng phân lập, máy trạm Linux phục vụ thực hành bảo mật và CTF.',
  },
  {
    id: 'room-c304',
    name: 'Phòng Hội Thảo Nhóm C304',
    building: 'C',
    floor: 3,
    capacity: 12,
    equipment: ['projector', 'whiteboard', 'ac'],
    photoUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    description: 'Phòng họp trang bị màn hình thông minh cảm ứng Interactive Smartboard 75 inch.',
  },
  {
    id: 'room-v101',
    name: 'VKU MakerSpace V101',
    building: 'V',
    floor: 1,
    capacity: 40,
    equipment: ['high_spec_pc', 'projector', 'whiteboard', 'ac'],
    photoUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    description: 'Khu vực sáng chế phần cứng, robotics, máy in 3D và bàn gia công thử nghiệm mạch IoT.',
  },
  {
    id: 'room-v201',
    name: 'Phòng Khởi Nghiệp V201',
    building: 'V',
    floor: 2,
    capacity: 10,
    equipment: ['projector', 'whiteboard', 'ac'],
    photoUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80',
    status: 'occupied',
    description: 'Phòng ươm tạo dự án sinh viên khởi nghiệp, có khu vực pitching và ghi hình demo sản phẩm.',
  },
  {
    id: 'room-v302',
    name: 'Phòng Lập Trình Mobile V302',
    building: 'V',
    floor: 3,
    capacity: 20,
    equipment: ['high_spec_pc', 'ac', 'projector'],
    photoUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    description: 'Dàn iMac và trạm thử nghiệm thiết bị Android/iOS dành cho các lớp phát triển đa nền tảng.',
  },
  {
    id: 'room-v401',
    name: 'Phòng Studio Podcast & Seminar V401',
    building: 'V',
    floor: 4,
    capacity: 5,
    equipment: ['ac', 'high_spec_pc', 'whiteboard'],
    photoUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=80',
    status: 'available',
    description: 'Phòng cách âm chuyên nghiệp thu âm nội dung học tập số và tọa đàm công nghệ sinh viên.',
  },
];
